PUT http://localhost:8080/events/3
content-type: application/json

{
  "name": "Updated test event",
  "description": "An updated test event",
  "location": "Test location (updated!)",
  "dateTime": "2025-01-02T15:30:00Z"
}
